### ISSUE TITLE
json5 - 6

### ISSUE THREAD

**Issue by ithinkido** [yknivag/ESP_OTA_GitHub#1]
Thanks for the great work on this repository.
Would it be possible for an update form Json5 to Json6 ? 
and when trying the example I seem to be getting a few errors about the SSL certs:

no matching function for call to 'BearSSL::CertStore::initCertStore(fs::FS&, const char*, const char*)'

I realise I am missing something here, but would it be possible to add a bit in the readme about how to generate this part ? (…)

from the readme:
Full instructions can be found at (...)

**Comment by yknivag** [comment]
Hi, thank you for using my little library.

The change from ArduinoJSON 5 to ArduinoJSON 6 is unfortunately complicated by the author of that library's decision to make many breaking changes.  This has affected many libraries.  As soon as I can get it to work I will update it.

"No matching function for call to `BearSSL::CertStore::initCertStore(fs::FS&, const char*, const char*)`" suggests that you have not got the correct version of the ESP8266WiFi installed.  The BearSSL library should be a part of that [see here](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WiFi/src).  These libraries are installed when the ESP8266 boards are installed in the boards manager using the official boards definitions.  Which version of the ESP8266 boards do you have installed?

Regarding the README file - thank you for pointing out the omission - I have updated it with instructions and links for generating and uploading the certificate file.

**Comment by ithinkido** [comment]
Thanks, I was on 2.5.2 and now after the update it is compiling perfectly.
I had not realised how much was involved in json update. I will just use 5 for now and swop when needed. Also thanks for the info in the readme. I am really looking forward to getting this working

**Comment by ithinkido** [comment]
have I understood this correct, the git user is just USERNAME ( ie not  https://github.com/USERNAME ) 
and the git repo would be :
https://github.com/USERNAME/REPO.git ?
I am getting this on upload:
fatal: not a git repository (or any of the parent directories): .git

**Comment by yknivag** [comment]
That is very promising. I'd be very interested to hear how you get on.

I haven't tested it yet, but have just this evening pushed a branch with code that compiles against ArduinoJSONv6.  If all goes well I will push it properly tomorrow.

I'm also working on a sort of showcase/demonstration repository that you can actually do a test upgrade against.

**Comment by yknivag** [comment]
GHOTA_USERNAME is just the username yes, so for this repo it would be "yknivag", for yours "ithinkido".

**Comment by ithinkido** [comment]
The showcase demo would be a super help for me to understand the setup. 
I tried setting ap ssid, psk, user name , (ithinkido) repo name ( as mentioned) and tag left unchanged 0.0.0, uploaded bin and set the bin name accordingly ( bin is tagged 1.0.0)
On compile I get no errors, but on  upload i get the warning mentioned previously about the repo. On the serial it outputs spiff data and certs read = 149 so think the ssl cert part is ok. But that is all that  happens. It does not seem to be connecting to the network ( i added a serial println after the wifi multi call and it does not appear.)

**Comment by yknivag** [comment]
Hopefully will all be coming over the weekend.

It seems WiFiMulti is a bit flaky in ESP8266v2.6.3. New example coming at the weekend using basic WiFi.

**Comment by ithinkido** [comment]
One thing I found when looking for info on bear:ssl was this comment on CPU speed. 
https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/bearssl-client-secure-class.html#cpu-requirements

**Comment by yknivag** [comment]
Yes, all the underlying requirements for https apply. They have to because GitHub don't support http.

Ultimately this library is just a wrapper for ESP8266httpUpdate(Secure) that adds the ability to check for new releases on GitHub. Anything needed for ESP8266Update, ESP8266Wifi and BearSSL will also be needed here.

When I push code tomorrow for ArduinoJSON v6 and to remove WiFiMulti I will try and make it clearer in the readme exactly what is required.

**Comment by ithinkido** [comment]
Thanks for the fantasic changes and the demo. It is all very clear and easy to use.

**Comment by yknivag** [comment]
You're very welcome.  Hope you find it useful.

**Comment by ithinkido** [comment]
VERY USEFUL !!!! I have just done the first test update and it went super smooth !!!!

**Comment by yknivag** [comment]
Fantastic. :-)
