### ISSUE TITLE
Generating certs script does not seem to working any more

### ISSUE THREAD

**Issue by ithinkido** [yknivag/ESP_OTA_GitHub#10]
I revisited this project after a while , looking to add it to a new project I am working on.  I tried to generate a new set of SSL certs using the python script, but It seems to no longer be working.
I am using python 3.10.6 on Ubuntu.
When running the script these are the error logs
```
user@dell:$python ESP_OTA_GitHub_Showcase/certs-from-mozilla.py
AC Camerfirma, S.A.:AC Camerfirma SA CIF A82743287:http://www.chambersign.org/ -> data/ca_000.der
Could not read certificate from <stdin>
Unable to load certificate
AC Camerfirma, S.A.:AC Camerfirma S.A.: -> data/ca_000.der
Could not read certificate from <stdin>
Unable to load certificate
AC Camerfirma, S.A.:AC Camerfirma S.A.: -> data/ca_000.der
Could not read certificate from <stdin>
Unable to load certificate
Actalis:Actalis S.p.A./03358520967: -> data/ca_000.der
Could not read certificate from <stdin>
Unable to load certificate
...
...
...
```
Is there something that I am missing  here to make this work ? I do not recall having issues using this a while ago

**Comment by yknivag** [comment]
Hi,

The script is is maintained outside of this repo at https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WiFi/examples/BearSSL_CertStore

Do you have the same problem if you use the script directly from there?

Kind Regards,

Gavin.

**Comment by ithinkido** [comment]
Thanks for the link. That script is working for me.
