### ISSUE TITLE
Return on function.

### ISSUE THREAD

**Issue by diegorichi** [yknivag/ESP_OTA_GitHub#11]
Hello! I'm using your library with some small and quick modifications:

You have missing the return to this function bool ESPOTAGitHub::doUpgrade()

Please check: https://github.com/yknivag/ESP_OTA_GitHub/blob/ac82e3d3bf3f430c577e67510812e6b21446626d/src/ESP_OTA_GitHub.cpp#L262

That generates a compilation error.

**Comment by yknivag** [comment]
Hi,

Thanks for using the library, I hope you find it useful.

The return is handled in the switch statement at the end of the function, the code will never reach L262.

Kind Regards,

Gavin.

**Comment by diegorichi** [comment]
Hello!

Thank you for your response!! I'm glad to contribute.

You have right, but the compiler didn't like, and to use it, I had to add it.

You have the fix here: https://github.com/yknivag/ESP_OTA_GitHub/pull/6/files#diff-24377001bd2bc06847f061d16a0e56b272e6b50e67bedaa43e36da1dbec95f5eR263

As you see, in that commit the return at the end was added.
