### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by epiller** [yknivag/ESP_OTA_GitHub#3]
Does this library support TLS? Thinking of implementing it but it could be a huge security risk due to MITM attacks and such.

**Comment by yknivag** [comment]
The library relies on the underlying Espressif `ESP8266httpUpdate` for retrieval and flashing and that in turn relies on their implementation of BearSSL for https certificate authentication.

You can read the Espressif docs at https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/bearssl-client-secure-class.html

**Comment by epiller** [comment]
Thank you!

**Comment by yknivag** [comment]
To save you reading all through:

_Please see the BearSSL website for detailed cryptographic information. In general, TLS 1.2, TLS 1.1, and TLS 1.0 are supported with RSA and Elliptic Curve keys and a very rich set of hashing and symmetric encryption codes. Please note that Elliptic Curve (EC) key operations take a significant amount of time._
